version: '3.8'

services:
  books:
    container_name: books-authors
    build: ./
    command: ./books
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql-books_authors
    restart: always
    image: mysql:latest

    environment:
      - MYSQL_DATABASE=books_authors
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #recommended command to start on win os: --innodb_use_native_aio=0

    ports:
    - "3304:3306"

  #todo postgres

#if need volumes:
# - - my-datavolume:/var/lib/mysql
#volumes:
  #-my-datavolume